baseURL = "https://lpmotors.es"
title = "LPMotors"
author = "spamer"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/lpm-simple.svg"
    alt = "LPMotors Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-[40px] w-auto"

  [params.site]
    name = "LPMotors"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Una pagina sobre coches de lujo"
    meta_og_title = "LPMotors"
    meta_og_type = "website"
    meta_og_url = "https://lpmotors.es"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Una pagina sobre coches de lujo"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@spamer"
    meta_twitter_creator = "@spamer"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Coches"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Quienes somos"
    url = "/quienes-somos/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contacto/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/sermongar/lpmotors"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
